version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: sportmap_db
    environment:
      POSTGRES_USER: sportmap
      POSTGRES_PASSWORD: sportmap_password
      POSTGRES_DB: sportmap_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sportmap_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@grandstand.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin_data:
