"""align_scraper_data

Revision ID: 4d4813e79121
Revises: fece6598ee5f
Create Date: 2026-07-16 07:45:49.570732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d4813e79121'
down_revision: Union[str, Sequence[str], None] = 'fece6598ee5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(), nullable=True))
    op.add_column('events', sa.Column('organizer_raw', sa.String(), nullable=True))
    op.add_column('events', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('venues', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'region')
    op.drop_column('events', 'tags')
    op.drop_column('events', 'organizer_raw')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
