"""Add site knowledge

Revision ID: 665c38660c1f
Revises: 8de1450606ec
Create Date: 2026-07-16 06:51:35.468232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '665c38660c1f'
down_revision: Union[str, Sequence[str], None] = '8de1450606ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('page_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_flows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('site_type', sa.String(), nullable=True),
    sa.Column('has_events', sa.Integer(), nullable=True),
    sa.Column('has_members', sa.Integer(), nullable=True),
    sa.Column('has_results', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('proxy_tier', sa.String(), nullable=True),
    sa.Column('selectors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_mapped_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_knowledge_site_id'), 'site_knowledge', ['site_id'], unique=True)
    op.add_column('llm_usage', sa.Column('scraper_run_id', sa.UUID(), nullable=True))
    op.add_column('llm_usage', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('llm_usage_run_id_fkey'), 'llm_usage', type_='foreignkey')
    op.create_foreign_key(None, 'llm_usage', 'scraper_runs', ['scraper_run_id'], ['id'])
    op.drop_column('llm_usage', 'run_id')
    op.drop_column('llm_usage', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_usage', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('llm_usage', sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'llm_usage', type_='foreignkey')
    op.create_foreign_key(op.f('llm_usage_run_id_fkey'), 'llm_usage', 'scraper_runs', ['run_id'], ['id'])
    op.drop_column('llm_usage', 'timestamp')
    op.drop_column('llm_usage', 'scraper_run_id')
    op.drop_index(op.f('ix_site_knowledge_site_id'), table_name='site_knowledge')
    op.drop_table('site_knowledge')
    # ### end Alembic commands ###
