"""add_scraper_run

Revision ID: 87f5493bd80c
Revises: ec4d76f63da2
Create Date: 2026-07-01 16:35:31.044763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '87f5493bd80c'
down_revision: Union[str, Sequence[str], None] = 'ec4d76f63da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('events_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_runs')
    # ### end Alembic commands ###
