"""add research models

Revision ID: a9a5c27e0dba
Revises: 4d4813e79121
Create Date: 2026-08-11 09:30:25.353690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9a5c27e0dba'
down_revision: Union[str, Sequence[str], None] = '4d4813e79121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_entity_id'), 'research_notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_research_notes_entity_type'), 'research_notes', ['entity_type'], unique=False)
    op.create_table('graph_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_snapshots_sport_id'), 'graph_snapshots', ['sport_id'], unique=False)
    op.create_table('divisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('conference_name', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_competition_id'), 'divisions', ['competition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divisions_competition_id'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_graph_snapshots_sport_id'), table_name='graph_snapshots')
    op.drop_table('graph_snapshots')
    op.drop_index(op.f('ix_research_notes_entity_type'), table_name='research_notes')
    op.drop_index(op.f('ix_research_notes_entity_id'), table_name='research_notes')
    op.drop_table('research_notes')
    # ### end Alembic commands ###
