"""add content_hash column

Revision ID: ec4d76f63da2
Revises: 8c34b19784ac
Create Date: 2026-07-01 15:57:41.584628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ec4d76f63da2'
down_revision: Union[str, Sequence[str], None] = '8c34b19784ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_content_hash'), 'events', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_content_hash'), table_name='events')
    op.drop_column('events', 'content_hash')
    # ### end Alembic commands ###
