"""schema_improvements

Revision ID: fece6598ee5f
Revises: 665c38660c1f
Create Date: 2026-07-16 07:32:32.923604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fece6598ee5f'
down_revision: Union[str, Sequence[str], None] = '665c38660c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_sanctioners', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('competition_sanctioners', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_competition_sanctioners_competition_id'), 'competition_sanctioners', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_sanctioners_organization_id'), 'competition_sanctioners', ['organization_id'], unique=False)
    op.add_column('competitions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('competitions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_competitions_organizer_id'), 'competitions', ['organizer_id'], unique=False)
    op.add_column('discovery_sources', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('discovery_sources', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('discovery_sources', 'verified',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="verified::int::boolean")
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_events_competition_id'), 'events', ['competition_id'], unique=False)
    op.create_index(op.f('ix_events_end_date'), 'events', ['end_date'], unique=False)
    op.create_index(op.f('ix_events_season_id'), 'events', ['season_id'], unique=False)
    op.create_index(op.f('ix_events_sport_id'), 'events', ['sport_id'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.add_column('llm_usage', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('llm_usage', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_llm_usage_scraper_run_id'), 'llm_usage', ['scraper_run_id'], unique=False)
    op.add_column('org_relationships', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('org_relationships', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('scraper_runs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('scraper_runs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('scraper_runs', 'was_healed', server_default=None)
    op.alter_column('scraper_runs', 'was_healed',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="was_healed::int::boolean")
    op.alter_column('scraper_runs', 'was_healed', server_default=sa.text('false'))
    op.add_column('seasons', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('seasons', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_seasons_end_date'), 'seasons', ['end_date'], unique=False)
    op.create_index(op.f('ix_seasons_start_date'), 'seasons', ['start_date'], unique=False)
    op.add_column('site_knowledge', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('site_knowledge', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('site_knowledge', 'has_events',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="has_events::int::boolean")
    op.alter_column('site_knowledge', 'has_members',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="has_members::int::boolean")
    op.alter_column('site_knowledge', 'has_results',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="has_results::int::boolean")
    op.add_column('sports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'updated_at')
    op.drop_column('venues', 'created_at')
    op.drop_column('sports', 'updated_at')
    op.drop_column('sports', 'created_at')
    op.alter_column('site_knowledge', 'has_results',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('site_knowledge', 'has_members',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('site_knowledge', 'has_events',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('site_knowledge', 'updated_at')
    op.drop_column('site_knowledge', 'created_at')
    op.drop_index(op.f('ix_seasons_start_date'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_end_date'), table_name='seasons')
    op.drop_column('seasons', 'updated_at')
    op.drop_column('seasons', 'created_at')
    op.alter_column('scraper_runs', 'was_healed', server_default=None)
    op.alter_column('scraper_runs', 'was_healed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using="was_healed::int")
    op.alter_column('scraper_runs', 'was_healed', server_default=sa.text('0'))
    op.drop_column('scraper_runs', 'updated_at')
    op.drop_column('scraper_runs', 'created_at')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'created_at')
    op.drop_column('org_relationships', 'updated_at')
    op.drop_column('org_relationships', 'created_at')
    op.drop_index(op.f('ix_llm_usage_scraper_run_id'), table_name='llm_usage')
    op.drop_column('llm_usage', 'updated_at')
    op.drop_column('llm_usage', 'created_at')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_sport_id'), table_name='events')
    op.drop_index(op.f('ix_events_season_id'), table_name='events')
    op.drop_index(op.f('ix_events_end_date'), table_name='events')
    op.drop_index(op.f('ix_events_competition_id'), table_name='events')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.alter_column('discovery_sources', 'verified',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('discovery_sources', 'updated_at')
    op.drop_column('discovery_sources', 'created_at')
    op.drop_index(op.f('ix_competitions_organizer_id'), table_name='competitions')
    op.drop_column('competitions', 'updated_at')
    op.drop_column('competitions', 'created_at')
    op.drop_index(op.f('ix_competition_sanctioners_organization_id'), table_name='competition_sanctioners')
    op.drop_index(op.f('ix_competition_sanctioners_competition_id'), table_name='competition_sanctioners')
    op.drop_column('competition_sanctioners', 'updated_at')
    op.drop_column('competition_sanctioners', 'created_at')
    # ### end Alembic commands ###
